name: cypress tests

on:
  pull_request:
    branches:
      - current

jobs:
  start-workflow:
    name: start workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # actions/checkout@v3

      - name: install node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # actions/setup-node@v3
        with:
          node-version: '16.13.1'

      - name: npm install
        run: cd website && npm ci

      - name: setup env
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number ${{ github.event_path }})
          echo "PR_NUMBER=${PR_NUMBER}" >> ${GITHUB_ENV}

      - name: run cypress e2e 
        uses: cypress-io/github-action@248bde77443c376edc45906ede03a1aba9da0462 # cypress-io/github-action@v5
        with:
          command: npx cypress run
          browser: chrome
          working-directory: website
          spec: cypress/e2e/*.cy.js
          wait-on: https://deploy-preview-${{ env.PR_NUMBER }}--docs-getdbt-com.netlify.app
          wait-on-timeout: 600
        env:
          CYPRESS_BASE_URL: https://deploy-preview-${{ env.PR_NUMBER }}--docs-getdbt-com.netlify.app

      - name: Screenshot artifact upload
        uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
