name: Run ESLint Checks
on: push

jobs:
  eslint-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # actions/checkout@v3
    
    - name: Install Node
      uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # actions/setup-node@v3
      with:
        node-version: '18.12.0'
      
    - name: Cache Node Modules
      uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # actions/cache@v3
      id: cache-node-mods
      with:
        path: website/node_modules
        key: node-modules-cache-v3-${{ hashFiles('**/package.json', '**/package-lock.json') }}

    - name: Install Packages
      if: steps.cache-node-mods.outputs.cache-hit != 'true'
      run: cd website && npm ci
      
    - name: Run ESLint
      run: cd website && npm run lintAll
